"""empty message

Revision ID: 3fb3d96cd57d
Revises: 
Create Date: 2018-08-02 15:19:12.622300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb3d96cd57d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barycentres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bodies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('mass', sa.Integer(), nullable=True),
    sa.Column('density', sa.Integer(), nullable=True),
    sa.Column('equatRadius', sa.Integer(), nullable=True),
    sa.Column('meanRadius', sa.Integer(), nullable=True),
    sa.Column('polarRadius', sa.Integer(), nullable=True),
    sa.Column('flatterning', sa.Integer(), nullable=True),
    sa.Column('volumetricMeanRadius', sa.Integer(), nullable=True),
    sa.Column('escapeVelocity', sa.Integer(), nullable=True),
    sa.Column('rotationPeriod', sa.Integer(), nullable=True),
    sa.Column('axialTilt', sa.Integer(), nullable=True),
    sa.Column('northPRightAsc', sa.Integer(), nullable=True),
    sa.Column('northPDeclination', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('orbits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Integer(), nullable=True),
    sa.Column('barycentre', sa.Integer(), nullable=True),
    sa.Column('eccentricity', sa.Integer(), nullable=False),
    sa.Column('semiMajorAxis', sa.Integer(), nullable=False),
    sa.Column('inclination', sa.Integer(), nullable=False),
    sa.Column('longAscNode', sa.Integer(), nullable=False),
    sa.Column('ArgPeriapsis', sa.Integer(), nullable=False),
    sa.Column('epochTrueAnomaly', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barycentre'], ['barycentres.id'], ),
    sa.ForeignKeyConstraint(['body'], ['bodies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('barycentre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['barycentre_id'], ['barycentres.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barycentre_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('systems')
    op.drop_table('orbits')
    op.drop_table('bodies')
    op.drop_table('barycentres')
    # ### end Alembic commands ###
